version: '3'

services:
  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    restart: always
    command:
      - '--storage.tsdb.retention.time=1y'
      - '--storage.tsdb.retention.size=90GB'
      - '--config.file=/opt/bitnami/prometheus/conf/prometheus.yml'
      - '--storage.tsdb.path=/opt/bitnami/prometheus/data'
      - '--web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries'
      - '--web.console.templates=/opt/bitnami/prometheus/conf/consoles'
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus_data:/opt/bitnami/prometheus/data
      - ./prometheus_config.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./grafana_data:/var/lib/grafana
  alertmanager:
    image: bitnami/alertmanager:latest
    volumes:
      #      - ./alertmanager_config.yml:/opt/bitnami/alertmanager/conf/config.yml
      - ./alertmanager_data:/opt/bitnami/alertmanager/data
  json_exporter:
    image: quay.io/prometheuscommunity/json-exporter
    command: --config.file=/config.yml
    container_name: json_exporter
    ports:
      - '7979:7979'
    restart: always
    volumes:
      - ./json_exporter_config.yml:/config.yml
  pushgateway:
    ports:
      - 9091:9091
    image: prom/pushgateway
    restart: always